import PdfCleanupForm from "@/components/admin/PdfCleanupForm";
import CoverCleanupForm from "@/components/admin/CoverCleanupForm";
import type { Metadata } from "next";
import Link from "next/link";
import { getAdminArticles, pageNumber } from "@/lib/journal/queries";
import { formatDate } from "@/lib/journal/types";
import DeleteForm from "@/components/admin/DeleteForm";
import styles from "../../admin.module.css";
export const metadata: Metadata = { title: "Manage articles" };
export default async function ArticlesPage({ searchParams }: { searchParams: Promise<{ page?: string; notice?: string }> }) {
  const params = await searchParams; const page = pageNumber(params.page);
  const { articles, count } = await getAdminArticles(page);
  return <section><div className={styles.heading}><div><p className="eyebrow">Your writing</p><h1>Articles</h1></div><Link href="/admin/articles/new" className="button">New Article</Link></div>{params.notice === "saved" && <p className={styles.success} role="status">Article saved.</p>}{(params.notice === "cover-cleanup" || params.notice === "cover-delete-cleanup") && <p className={styles.error} role="alert">Article {params.notice === "cover-delete-cleanup" ? "deleted" : "saved"}, but attachment cleanup was incomplete. Use Image maintenance or PDF maintenance below after 24 hours to retry cleanup.</p>}<CoverCleanupForm /><PdfCleanupForm /><p className={styles.intro}>{count} articles · Most recently updated first</p>{!articles.length ? <div className={styles.panel}><h2>{count ? "No articles on this page" : "Your writing starts here."}</h2><p>{count ? "Return to the first page to browse your articles." : "Create your first article and save it as a draft when you’re ready."}</p><Link className="text-link" href={count ? "/admin/articles" : "/admin/articles/new"}>{count ? "First page" : "Write an article"} →</Link></div> : <div className={styles.tableScroll}><table className={styles.table}><caption className="sr-only">Articles and publishing status</caption><thead><tr>{["Title", "Category", "Status", "Featured", "Published", "Updated", "Actions"].map(title => <th key={title} scope="col">{title}</th>)}</tr></thead><tbody>{articles.map(article => <tr key={article.id}><th scope="row"><Link href={"/admin/articles/" + article.id + "/edit"}>{article.title}</Link><span className={styles.slug}>/{article.slug}</span></th><td>{article.categories?.name ?? "Uncategorised"}</td><td><span className={styles.badge}>{article.status}</span></td><td>{article.featured ? "Yes" : "No"}</td><td>{formatDate(article.published_at)}</td><td>{formatDate(article.updated_at)}</td><td><Link className="text-link" href={"/admin/articles/" + article.id + "/edit"}>Edit <span className="sr-only">{article.title}</span></Link><DeleteForm kind="article" id={article.id} title={article.title} /></td></tr>)}</tbody></table></div>}<nav className={styles.pagination} aria-label="Article pages">{page > 1 && <Link href={"/admin/articles?page=" + (page - 1)}>← Previous</Link>}<span>Page {page} of {Math.max(1, Math.ceil(count / 30))}</span>{page * 30 < count && <Link href={"/admin/articles?page=" + (page + 1)}>Next →</Link>}</nav></section>;
}
