import { publicPageMetadata } from "@/lib/site-metadata";
import Link from "next/link";
import ReadingCTA from "@/components/ReadingCTA";
import Arrow from "@/components/Arrow";

export const metadata = publicPageMetadata("/about", "About Me", "Meet Razaq and explore the thoughts, reflections and questions behind Razaq Thoughts.");

export default function AboutPage() {
  return <div className="container"><header className="page-intro about-intro"><p className="eyebrow category-label">About Me</p><h1>Ideas bring us closer.<br /><em>Conversation takes us further.</em></h1><p>I’m Razaq. Welcome to my personal website, where I share articles, thoughts, reflections and other writing.</p></header><section className="about-mission" aria-labelledby="mission-title"><div className="about-emblem" aria-hidden="true"><span>RT</span><p>READ. REFLECT. DISCUSS.</p></div><div><p className="eyebrow category-label">Why I write</p><h2 id="mission-title">A space to think,<br />and to think again.</h2><p>I write to explore ideas, make sense of experiences and ask better questions. My interests take me from technology and education to society, culture and everyday life.</p><p>The writing here reflects my own thoughts and experiences. I share it as part of an ongoing conversation, with room to learn, reconsider and see things differently.</p></div></section><section className="section-space" aria-labelledby="expect-title"><div className="section-heading"><div><p className="eyebrow category-label">What you can expect</p><h2 id="expect-title">Curiosity, with intention.</h2></div></div><div className="principles-grid"><article><span className="principle-number">01</span><h3>Thoughtful reading</h3><p>Clear, approachable writing that gives ideas the attention they deserve and leaves room for reflection.</p></article><article><span className="principle-number">02</span><h3>Different perspectives</h3><p>Questions across disciplines, grounded in everyday experience and open to more than one point of view.</p></article><article><span className="principle-number">03</span><h3>Considered discussion</h3><p>A commitment to respectful exchange, where readers can question ideas without attacking the people behind them.</p></article></div></section><section className="about-discussion"><p className="eyebrow category-label">An invitation to you</p><h2>You don’t have to agree<br /><em>to be part of the conversation.</em></h2><p>You’re welcome to leave a comment on my articles. Share an experience, ask a question or offer a different interpretation. Please stay respectful; comments are reviewed before they appear publicly.</p><Link className="text-link" href="/contact">Get in touch <Arrow /></Link></section><ReadingCTA /></div>;
}
