"use client";
import {useState} from "react";
import {inspectNewSimulationAction,prepareNewSimulationAction,confirmNewSimulationAction} from "@/app/admin/(protected)/simulation-actions";
import type {NewSimulationArticle,StoredSimulationPreview} from "@/lib/journal/new-comment-simulation";
type Row = NewSimulationArticle & {text:string;preview?:StoredSimulationPreview;message?:string;outcome?:"seeded"|"skipped"|"failed"|"waiting";count?:number};
export default function NewSimulationWorkflow(){
 const [rows,setRows]=useState<Row[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 function patch(id:string,change:Partial<Row>){setRows(previous=>previous?.map(row=>row.id===id?{...row,...change}:row)??null);}
 async function inspect(){setBusy(true);setError("");try{const found=await inspectNewSimulationAction();setRows(found.map(a=>({...a,text:a.preparedDataset??""})));}catch{setError("Unable to inspect articles. Check your administrator session and database connection.");}finally{setBusy(false);}}
 async function prepare(row:Row){setBusy(true);patch(row.id,{preview:undefined,message:undefined,outcome:undefined});try{const response=await prepareNewSimulationAction(row.id,row.text);if(response.error)patch(row.id,{message:response.error,outcome:response.error.startsWith("Not yet eligible")?"waiting":"failed"});else if(response.result?.status==="skipped")patch(row.id,{alreadySimulated:true,outcome:"skipped",message:"Already simulated"});else patch(row.id,{preview:response.result as StoredSimulationPreview});}catch{patch(row.id,{outcome:"failed",message:"Preview request failed. No confirmation was sent."});}finally{setBusy(false);}}
 async function confirm(row:Row){if(!row.preview||!window.confirm("Insert exactly these "+row.preview.comments.length+" reviewed comments with the displayed UTC timestamps?"))return;setBusy(true);try{const response=await confirmNewSimulationAction(row.preview.id,true);if(response.error)patch(row.id,{message:response.error,outcome:"failed"});else if(response.result)patch(row.id,{outcome:response.result.status,count:response.result.count,alreadySimulated:true,preview:undefined,message:response.result.status==="seeded"?"Inserted exactly as previewed.":"Already simulated"});}catch{patch(row.id,{outcome:"failed",message:"Confirmation outcome unknown. Inspect again before retrying; the ledger prevents duplicates."});}finally{setBusy(false);}}
 return <div><button className="button" disabled={busy} onClick={inspect}>Seed New Published Articles</button>
 <p>Inspect unseeded articles, prepare 25 comments specifically for each article, and review the full selected batch before confirming. All dates and times below are UTC.</p>
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">Processing…</p>}
 {rows&&<><p aria-live="polite">Published articles: {rows.length}. Already simulated: {rows.filter(r=>r.alreadySimulated&&r.outcome!=="seeded").length}. Newly seeded: {rows.filter(r=>r.outcome==="seeded").length}. Skipped/not yet eligible: {rows.filter(r=>r.outcome==="skipped"||r.outcome==="waiting").length}. Failures: {rows.filter(r=>r.outcome==="failed").length}. Total comments created: {rows.reduce((sum,r)=>sum+(r.count??0),0)}.</p>
 {rows.map(row=><article className="admin-comment-card" key={row.id}><h3>{row.title}</h3>{row.alreadySimulated?<p>{row.message??"Already simulated"}</p>:<>
 <details><summary>Read article and prepare its dataset</summary><p>{row.source?.excerpt}</p><p>Category: {row.source?.category}. Published: {row.source?.publishedAt??"Missing publication time"}.</p><div style={{whiteSpace:"pre-wrap"}}>{row.source?.content}</div><p>Write 25 distinct comments based on this full article. Fill the JSON comments array with those strings. The eight engagementAnchors values are distinct zero-based indexes identifying agreement, disagreement, question, observation, reflection, clarification, connection and alternative interpretation. Keep the supplied fingerprint. Names and times are assigned when preparing the preview.</p>
 <label htmlFor={"dataset-"+row.id}>Article-specific prepared dataset (JSON)</label><textarea id={"dataset-"+row.id} rows={14} style={{width:"100%"}} disabled={busy} value={row.text} onChange={e=>patch(row.id,{text:e.target.value,preview:undefined})}/></details>
 <button disabled={busy} onClick={()=>prepare(row)}>Prepare detailed preview</button>
 {row.message&&<p role="status">{row.message}</p>}
 {row.preview&&<div><h4>{row.preview.comments.length} comments — full preview</h4><p>Preview expires: {row.preview.expiresAt}. Confirmation preserves these exact names, comments and timestamps.</p><ol>{row.preview.comments.map((c,i)=><li key={i}><strong>{c.name}</strong><p><time dateTime={c.created_at}>{c.created_at.replace("T"," ").replace("Z"," UTC")}</time></p><p style={{whiteSpace:"pre-wrap"}}>{c.content}</p></li>)}</ol><button className="button" disabled={busy} onClick={()=>confirm(row)}>Confirm this exact batch</button><button disabled={busy} onClick={()=>patch(row.id,{preview:undefined})}>Discard preview</button></div>}
 </>}</article>)}</>}
 </div>;
}
